name: Keep Streamlit Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -fsS https://urlconverter-gbqjtnrs6padndtgialfur.streamlit.app/ \
            || (echo "🔴 Ping failed" && exit 1)
